# Generated by Django 2.1.7 on 2019-04-03 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='listing_ide',
            new_name='listing_id',
        ),
    ]
