# Generated by Django 2.1.7 on 2019-04-05 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20190403_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
