# Generated by Django 2.1.7 on 2019-03-14 13:41

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photos/realtors')),
                ('description', models.TextField(blank=True)),
                ('phone', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999999999)])),
                ('ismvp', models.BooleanField(default=False)),
                ('hireddate', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
